#define _BOOT_BOOT_VER 			0x01
#define _BOOT_HW_TYPE 			0x02 // Тип устройства!!!!!!!! Важно! Заполнить для каждого устройства
#define _BOOT_HW_VER  			0x03 // Железная версия устройства
#define _BOOT_PAGE_SIZE_POW 		7 // Размер страницы 2^pow 7 == 128
#define _BOOT_FW_PAGE_START 		0x08000200 // начало прошивки
#define _BOOT_FLASH_SIZE 		0x4000 // полный размер флеша

//#define BOOT_LPUART1_A_1
//#define BOOT_LPUART1_A_4		
#define BOOT_LPUART1_A_14 //SWCLK
//#define BOOT_USART2_A_9
//#define BOOT_USART2_A_14 //SWCLK


#ifdef BOOT_LPUART1_A_1
	#define BOOT_UART 				LPUART1
	#define BOOT_UART_PORT 			GPIOA	
	#define BOOT_UART_BRR			(256*SYS_CLK_FREQ_KHZ*1000)/9600
	#define BOOT_GPIO_OPEN_DRAIN		GPIO_OTYPER_OT_1
	#define BOOT_GPIO_PULL_UP_MSK	GPIO_PUPDR_PUPD1_Msk
	#define BOOT_GPIO_PULL_UP_VAL	GPIO_PUPDR_PUPD1_0
	#define BOOT_GPIO_AFR_NUM		0	// 0..7 pin
	#define BOOT_GPIO_AFR_MSK		GPIO_AFRL_AFSEL1_Msk
	#define BOOT_GPIO_AFR			6 // AF6 для LPUART1
	#define BOOT_GPIO_AFR_POS		GPIO_AFRL_AFSEL1_Pos
	#define BOOT_GPIO_MODER_MSK		GPIO_MODER_MODE1_Msk
	#define BOOT_GPIO_MODER_VAL      GPIO_MODER_MODE1_1
#endif 
#ifdef BOOT_LPUART1_A_4
	#define BOOT_UART 				LPUART1
	#define BOOT_UART_PORT 			GPIOA	
	#define BOOT_UART_BRR			(256*SYS_CLK_FREQ_KHZ*1000)/9600
	#define BOOT_GPIO_OPEN_DRAIN		GPIO_OTYPER_OT_4
	#define BOOT_GPIO_PULL_UP_MSK	GPIO_PUPDR_PUPD4_Msk
	#define BOOT_GPIO_PULL_UP_VAL	GPIO_PUPDR_PUPD4_0
	#define BOOT_GPIO_AFR_NUM		0	// 0..7 pin
	#define BOOT_GPIO_AFR_MSK		GPIO_AFRL_AFSEL4_Msk
	#define BOOT_GPIO_AFR			6 // AF6 для LPUART1
	#define BOOT_GPIO_AFR_POS		GPIO_AFRL_AFSEL4_Pos
	#define BOOT_GPIO_MODER_MSK		GPIO_MODER_MODE4_Msk
	#define BOOT_GPIO_MODER_VAL      GPIO_MODER_MODE4_1
#endif 
#ifdef BOOT_LPUART1_A_14
	#define BOOT_UART 				LPUART1
	#define BOOT_UART_PORT 			GPIOA	
	#define BOOT_UART_BRR			(256*SYS_CLK_FREQ_KHZ*1000)/9600
	#define BOOT_GPIO_OPEN_DRAIN		GPIO_OTYPER_OT_14
	#define BOOT_GPIO_PULL_UP_MSK	GPIO_PUPDR_PUPD14_Msk
	#define BOOT_GPIO_PULL_UP_VAL	GPIO_PUPDR_PUPD14_0
	#define BOOT_GPIO_AFR_NUM		1	// 8..16 pin
	#define BOOT_GPIO_AFR_MSK		GPIO_AFRH_AFSEL14_Msk
	#define BOOT_GPIO_AFR			6 // AF6 для LPUART1
	#define BOOT_GPIO_AFR_POS		GPIO_AFRH_AFSEL14_Pos
	#define BOOT_GPIO_MODER_MSK		GPIO_MODER_MODE14_Msk
	#define BOOT_GPIO_MODER_VAL      GPIO_MODER_MODE14_1
#endif 
#ifdef BOOT_USART2_A_9
	#define BOOT_UART 				USART2
	#define BOOT_UART_PORT 			GPIOA	
	#define BOOT_UART_BRR			(SYS_CLK_FREQ_KHZ*1000)/9600
	#define BOOT_GPIO_OPEN_DRAIN		GPIO_OTYPER_OT_9
	#define BOOT_GPIO_PULL_UP_MSK	GPIO_PUPDR_PUPD9_Msk
	#define BOOT_GPIO_PULL_UP_VAL	GPIO_PUPDR_PUPD9_0
	#define BOOT_GPIO_AFR_NUM		1	// 8..16 pin
	#define BOOT_GPIO_AFR_MSK		GPIO_AFRH_AFSEL9_Msk
	#define BOOT_GPIO_AFR			4 // AF6 для LPUART1
	#define BOOT_GPIO_AFR_POS		GPIO_AFRH_AFSEL9_Pos
	#define BOOT_GPIO_MODER_MSK		GPIO_MODER_MODE9_Msk
	#define BOOT_GPIO_MODER_VAL      GPIO_MODER_MODE9_1
#endif 
#ifdef BOOT_USART2_A_14
	#define BOOT_UART 				USART2
	#define BOOT_UART_PORT 			GPIOA	
	#define BOOT_UART_BRR			(SYS_CLK_FREQ_KHZ*1000)/9600
	#define BOOT_GPIO_OPEN_DRAIN		GPIO_OTYPER_OT_14
	#define BOOT_GPIO_PULL_UP_MSK	GPIO_PUPDR_PUPD14_Msk
	#define BOOT_GPIO_PULL_UP_VAL	GPIO_PUPDR_PUPD14_0
	#define BOOT_GPIO_AFR_NUM		1	// 8..16 pin
	#define BOOT_GPIO_AFR_MSK		GPIO_AFRH_AFSEL14_Msk
	#define BOOT_GPIO_AFR			4 // AF6 для LPUART1
	#define BOOT_GPIO_AFR_POS		GPIO_AFRH_AFSEL14_Pos
	#define BOOT_GPIO_MODER_MSK		GPIO_MODER_MODE14_Msk
	#define BOOT_GPIO_MODER_VAL      GPIO_MODER_MODE14_1
#endif 

#define _BOOT_PAGES_FOR_WRITE 	((0x08000000 + _BOOT_FLASH_SIZE - _BOOT_FW_PAGE_START) >> _BOOT_PAGE_SIZE_POW)